openapi: "3.0.0"
info:
  title: Thing Description Registry
  version: 0.7.1
paths:
  /public/things:
    get:
      description: Returns all registered thing descriptions
      parameters:
      - in: query
        name: page_size
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 50
        required: false
        description: Limit the number of returned thing descriptions by page
        example: 30
      - in: query
        name: page
        schema:
          type: integer
          example: 1
          minimum: 1
          default: 1
        required: false
        description: Return the page of thing descriptions
      - in: query
        name: resolve
        schema:
          type: boolean
        required: false
        description: Resolve all thing descriptions
        example: false
      - in: query
        name: owner
        schema:
          type: array
          items:
            type: string
            example: test@example.com
        required: false
        description: Filter by owner
      - in: query
        name: type
        schema:
          type: array
          items:
            type: string
            example: iot:PowerMonitoring
        required: false
        description: Type(s) of the thing
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Things"
  /public/things/{id}:
    get:
      description: Returns a specific thing description
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/td+json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
            application/ld+json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
            application/json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
        '404':
          description: Thing description not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /things:
    get:
      description: Returns all registered thing descriptions
      parameters:
      - in: query
        name: page_size
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 50
        required: false
        description: Limit the number of returned thing descriptions by page
        example: 30
      - in: query
        name: page
        schema:
          type: integer
          example: 1
          minimum: 1
          default: 1
        required: false
        description: Return the page of thing descriptions
      - in: query
        name: resolve
        schema:
          type: boolean
        required: false
        description: Resolve all thing descriptions
        example: false
      - in: query
        name: owner
        schema:
          type: array
          items:
            type: string
            example: test@example.com
        required: false
        description: Filter by owner
      - in: query
        name: type
        schema:
          type: array
          items:
            type: string
            example: iot:PowerMonitoring
        required: false
        description: Type(s) of the thing
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Things"
    post:
      description: Creates a new thing description
      requestBody:
        description: Thing description added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThingDescription'
      responses:
        '201':
          description: Successful operation
          headers:
              location:
                schema:
                  type: string
                  description: Location of the new thing description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatedThing"
        '400':
          description: Invalid description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
  /things/{id}:
    get:
      description: Returns a specific thing description
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/td+json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
            application/ld+json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
            application/json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
        '404':
          description: Thing description not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      description: Update a specific thing description
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      requestBody:
        description: Updated thing description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThingDescription'
      responses:
        '200':
          description: Thing description updated
        '400':
          description: Invalid thing description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"      
        '404':
          description: Thing description not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: Delete a specific thing description
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Thing description deleted
        '404':
          description: Thing description not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /things/{id}/openapi:
    get:
      description: Returns a specific thing description converted to openapi
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ThingDescription"
        '404':
          description: Thing description not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /things/{id}/{security}/credentials:
    put:
      description: Updates the credentials of thing. Only the owner can update credentials.
      parameters:
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      - name: security
        in: path
        description: Name of the security
        example: basic_sc
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '404':
          description: Description not found
          content:
            application/json:
              example:
                {
                  "status": 404,
                  "error": "description_not_found",
                  "message": "Description not found"
                }
        '200':
          description: Successful operation
          content:
            application/json:
              example:
                {
                  "password": "string",
                  "username": "string"
                }
    get:
      description: Return the credentials of thing. Only the owner can return credentials.
      parameters:
      - name: security
        in: path
        description: Name of the security
        example: basic_sc
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: ID of the thing description
        example: uri:urn:6f0685ad-8a08-431a-b700-6dd1a236335b
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
  /query:
    get:
      description: Query thing descriptions
      parameters:
      - in: query
        name: jsonpath
        schema:
          type: string
          example: $.properties.* ? (@.type == "iot:PowerMonitoring")
        required: false
        description: A jsonpath query
      responses:
        '200':
          description: Returns query result
          content:
            application/json:
              schema:
                type: array
              example:
                [
                  {
                    "result": {
                      "type": "string",
                      "forms": [
                        {
                          "op": [
                            "readproperty",
                            "writeproperty"
                          ],
                          "href": "https://mylamp.example.com/status",
                          "contentType": "application/json"
                        }
                      ],
                      "readOnly": false,
                      "writeOnly": false,
                      "observable": false
                    }
                  }
                ]
  /validate:
    post:
      description: Validates a thing description
      requestBody:
        description: Thing description to validate
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThingDescription'
      responses:
        '201':
          description: Successful operation
        '400':
          description: Thing description is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
  /version:
    get:
      description: Returns the version of the registry
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerVersion'
components:
  schemas:
    ServerVersion:
      type: object
      properties: 
        version:
          type: string
          description: The version of the registry service
          example: 0.3.5
    CreatedThing:
      type: object
      description: Returns the created thing id
      properties:
        id: 
          type: string
          example: uri:urn:2b504eab-b0c5-46e1-abf2-b849f1b53cbb
      required: 
        - id
    ThingDescription:
      type: object
      description: A valid W3C Thing Description (https://w3c.github.io/wot-thing-description/) 
      example:
        {
          "@context": "https://www.w3.org/2019/wot/td/v1",
          "id": "urn:dev:ops:32473-WoTLamp-1234",
          "title": "MyLampThing",
          "securityDefinitions": {
              "basic_sc": {"scheme": "basic", "in":"header"}
          },
          "security": ["basic_sc"],
          "properties": {
              "status" : {
                  "type": "string",
                  "forms": [{"href": "https://mylamp.example.com/status"}]
              }
          },
          "actions": {
              "toggle" : {
                  "forms": [{"href": "https://mylamp.example.com/toggle"}]
              }
          },
          "events":{
              "overheating":{
                  "data": {"type": "string"},
                  "forms": [{
                      "href": "https://mylamp.example.com/oh",
                      "subprotocol": "longpoll"
                  }]
              }
          }
      }
    Things:
      type: object
      properties:
        page:
          type: integer
          description: The current page number
        pageSize:
          type: integer
          description: The current page size
        totalPages:
          type: integer
          description: The total number of pages
        hasNextPage:
          type: boolean
          description: True if there is a next page
        things:
          type: array
          items:
            $ref: "#/components/schemas/Thing"
    Thing:
      type: object
      description: A summary for a stored thing
      properties:
        id:
          type: string
          description: Unique identifier of the thing
          example: uri:urn:b960ec68-5ef8-4f54-a50c-2a5a347730d1
        title:
          type: string
          description: The title of the ting description
          example: My Example Thing
        description:
          $ref: "#/components/schemas/ThingDescription"
        types:
          type: array
          description: Semantic types of the thing 
          example:
            [
              "iot:BinarySwitchControl",
              "iot:PowerMonitoring"
            ]
          items:
            type: string
            description: Semantic type of a thing
        owner:
          type: string
          description: Name of the owner
          example: household1235@foresight-plattform.de
        href:
          type: string
          format: uri
          description: Link to the full thing description
      required:
        - id
        - title
        - types
        - owner
        - href
    Credentials:
      type: object
      oneOf:
        - $ref: '#/components/schemas/BasicCredentials'
        - $ref: '#/components/schemas/BearerCredentials'
        - $ref: '#/components/schemas/ApiKeyCredentials'
    BasicCredentials: 
      type: object
      required:
        - username
        - password
      additionalProperties: false
      properties: 
        username: 
          type: string
          description: Username of the basic authentication
        password:
          type: string
          description: Password of the basic authentication
    BearerCredentials: 
      type: object
      required:
        - token
      additionalProperties: false
      properties: 
        token: 
          type: string
          description: The bearer token to use
    ApiKeyCredentials:
      type: object
      additionalProperties: false
      properties:
        apiKey:
          type: string
          description: The api key to use
    DiscoveredThing:
      type: object
      properties:
        id: 
          type: string
          description: id of the discovered thing
          example: uri:urn:c5a6792a-2d7d-4be3-a6b6-9d1f21cf0490
        foundAt:
          type: string
          description: time when the thing was discovered
          example: 2021-03-30T07:06:31.930Z
        title: 
          type: string
          description: title of the discovered thing
          example: MyThing
        types: 
          type: array
          items: 
            type: string
          description: semantic types of the discovered thing
        source:
          type: string
          description: name of the plugin that discovered the thing
          example: thingsboard-importer
        description: 
          $ref: '#/components/schemas/ThingDescription'
    DiscoveredThings:
      type: object
      properties:
        page:
          type: integer
          description: The current page number
        pageSize:
          type: integer
          description: The current page size
        totalPages:
          type: integer
          description: The total number of pages
        hasNextPage:
          type: boolean
          description: True if there is a next page
        things:
          type: array
          items:
            $ref: "#/components/schemas/DiscoveredThing" 
    Plugins:
      type: array
      items:
        $ref: "#/components/schemas/Plugin"
    Plugin:
      type: object
      properties: 
        name: 
          type: string
          description: Type of the plugin
        version:
          type: string
          description: Version of the plugin
          example: 0.0.1
        author:
          type: string
          description: Email of the author
          example: sebastian.alberternst@dfki.de
        description:
          type: string
          description: Description of the plugin
        previewImage:
          type: string
          format: uri
          description: Link to an image for the plugin
        schema:
          $ref: "#/components/schemas/PluginSchema"
        settings:
          $ref: "#/components/schemas/PluginSettings"
    PluginSchema:
      description: A json schema describing the plugin settings 
      type: object
    PluginSettings:
      description: Plugin settings described by the plugin schema
      oneOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
    Error:
      type: object
      properties:
        status: 
          type: integer
          description: http status
        code: 
          type: string
          description: "error type"
        message: 
          type: string
          description: "Human readable error code"
      required:
        - message
        - code
        - status
    ValidationError:
      allOf:  
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - info
          properties:
            info:
              type: array
              items:
                type: object
                properties:
                  keyword: 
                    type: string
                  dataPath: 
                    type: string
                  schemaPath: 
                    type: string
                  params: 
                    type: object
                    properties: 
                      missingProperty: 
                        type: string
                  message: 
                    type: string
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT