openapi: "3.0.0"
info:
  title: Thing Description Registry / Directory
  version: 0.3.6
servers:
- url: https://thing-registry.apps.foresight.aareon.com/api/
  description: Foresight Thing Registry 
paths:
  /things:
    get:
      description: Returns all registered thing descriptions
      security:
        - auth:
          - registry.thing.read
    post:
      description: Creates a new thing description
      security:
        - auth:
          - registry.thing.create
  /things/{id}:
    get:
      description: Returns a specific thing description
      security:
        - auth:
          - registry.thing.read
    put:
      description: Update a specific thing description
      security:
        - auth:
          - registry.thing.update
    delete:
      description: Delete a specific thing description
      security:
        - auth:
          - registry.thing.delete
  /affordances:
    get:
      description: Lists affordances
      security:
        - auth:
          - registry.thing.read
  /query:
    get:
      description: Lists affordances
      security:
        - auth:
          - registry.thing.read
  /validate:
    post:
      description: Validates a thing description
      security:
        - auth:
          - registry.thing.validate
  /version:
    get:
      description: Returns the version of the registry
  /plugins:
    get:
      description: Returns all plugins
      security:
        - auth:
          - registry.plugin.read
  /plugins/{id}:
    get:
      description: Return a plugin description
      security:
        - auth:
          - registry.plugin.read
  /plugins/{id}/settings:
    put:
      description: Update the settings of a plugin
      security:
        - auth:
          - registry.plugin.write
  /discovery/run:
    put:
      description: Discover things
      security:
        - auth:
          - registry.plugin.discover
  /discovery/things:
    get:
      description: Returns a list of discovered things
      security:
        - auth:
          - registry.plugin.discover
  /discovery/things/{thingId}:
    get:
      description: Returns a discovered thing by ID
      security:
        - auth:
          - registry.plugin.discover       
  /discovery/import:
    put:
      description: Import discovered things
      security:
        - auth:
          - registry.plugin.discover
  /permissions:
    get:
      description: Get all permissions of the current user
      security:
        - auth:
          - registry.permissions.read 
    post:
      description: Creates a new permission
      security:
        - auth:
          - registry.permission.create
  /permissions/{id}:
    get:
      description: Get a permission
      security:
        - auth:
          - registry.permissions.read 
    delete:
      description: Delete a permission
      security:
        - auth:
          - registry.permissions.delete 
components:
  securitySchemes:
    auth:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/auth'
          tokenUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/token'
          scopes:
            registry.thing.read: ability to read thing descriptions
            registry.thing.create: create a thing description
            registry.thing.update: update a thing description
            registry.thing.delete: delete a thing description
            registry.thing.validate: validate a thing description
            registry.plugin.read: read plugins
            registry.plugin.write: write plugins settings
            registry.plugin.discover: use plugins to discover new things
            registry.permission.create: create permissions
            registry.permission.read: read permissions
            registry.permission.delete: delete permission