openapi: "3.0.0"
info:
  title: Thing Description Registry / Directory
  version: 0.3.6
servers:
- url: https://thing-registry.apps.foresight.aareon.com/api/
  description: Foresight Thing Registry 
paths:
  /things:
    get:
      description: Returns all registered thing descriptions
      security:
        - auth:
          - registry.thing.read
    post:
      description: Creates a new thing description
      security:
        - auth:
          - registry.thing.create
  /things/{id}:
    get:
      description: Returns a specific thing description
      security:
        - auth:
          - registry.thing.read
    put:
      description: Update a specific thing description
      security:
        - auth:
          - registry.thing.update
    delete:
      description: Delete a specific thing description
      security:
        - auth:
          - registry.thing.delete
  /things/{id}/credentials:
    put:
      description: Updates the credentials of thing. Only the owner can update credentials.
      security:
        - auth:
          - registry.thing.credentials 
    get:
      description: Return the credentials of thing. Only the owner can return credentials.
      security:
        - auth:
          - registry.thing.credentials
  /things/{id}/access:
    get:
      description: Return information about the permissions and access right of the thing
      security:
        - auth:
          - registry.thing.read
  /things/{id}/targets:
    get:
      description: Return information about the targets of a thing
      security:
        - auth:
          - registry.targets.read
  /things/{id}/affordances/{type}/{name}/{index}/target:
    get:
      description: Return information about the targets of a thing
      security:
        - auth:
          - registry.targets.read
    put:
      description: Update a target of a thing
      security:
        - auth:
          - registry.targets.update
  /affordances:
    get:
      description: Lists affordances
      security:
        - auth:
          - registry.thing.read
  /query:
    get:
      description: Lists affordances
      security:
        - auth:
          - registry.thing.read
  /validate:
    post:
      description: Validates a thing description
      security:
        - auth:
          - registry.thing.validate
  /tickets:
     get:
      description: Return all tickets of the affordance of a specific user
      security:
        - auth:
          - registry.tickets.read
     post:
      description: Create a new ticket for a resource
      security:
        - auth:
          - registry.tickets.create
  /tickets/{id}:
     delete:
      description: Return all tickets of the affordance of a specific user
      security:
        - auth:
          - registry.tickets.delete
  /version:
    get:
      description: Returns the version of the registry
  /plugins:
    get:
      description: Returns all plugins
      security:
        - auth:
          - registry.plugin.read
  /plugins/{id}:
    get:
      description: Return a plugin description
      security:
        - auth:
          - registry.plugin.read
  /plugins/{id}/settings:
    put:
      description: Update the settings of a plugin
      security:
        - auth:
          - registry.plugin.write
  /discovery/run:
    put:
      description: Discover things
      security:
        - auth:
          - registry.plugin.discover
  /discovery/things:
    get:
      description: Returns a list of discovered things
      security:
        - auth:
          - registry.plugin.discover
  /discovery/things/{thingId}:
    get:
      description: Returns a discovered thing by ID
      security:
        - auth:
          - registry.plugin.discover       
  /discovery/import:
    put:
      description: Import discovered things
      security:
        - auth:
          - registry.plugin.discover
components:
  securitySchemes:
    auth:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/auth'
          tokenUrl: 'https://aareoniam.apps.foresight.aareon.com/auth/realms/foresight/protocol/openid-connect/token'
          scopes:
            registry.thing.read: ability to read thing descriptions
            registry.thing.create: create a thing description
            registry.thing.update: update a thing description
            registry.thing.delete: delete a thing description
            registry.thing.validate: validate a thing description
            registry.plugin.read: read plugins
            registry.plugin.write: write plugins settings
            registry.plugin.discover: use plugins to discover new things
            registry.thing.credentials: read and write thing credentials
            registry.thing.execute: execute forms of a thing
            registry.targets.read: read targets
            registry.targets.update: update targets
            registry.tickets.create: create tickets
            registry.tickets.update: update tickets
            registry.tickets.delete: delete tickets 