version: "3.1"

services:
  registry:
    build: .
    volumes:
      - ./index.js:/app/index.js
      - ./api-doc.yml:/app/api-doc.yml
      - ./lib:/app/lib
      - ./plugins:/app/plugins
      - ./config/registry/keycloak.json:/app/keycloak.json
    environment:
      NODE_ENV: development
      RESOURCE_SERVER_AUDIENCE: api-gateway
      KEYCLOAK_HOST: http://auth.192-168-178-60.nip.io
      KEYCLOAK_REALM: dataspace
      RESOURCE_CLIENT_ID: api-gateway
      RESOURCE_CLIENT_SECRET: 7SkmAdTp8xhL
    ports:
      - 8090:80
      - 9229:9229
    depends_on: 
      - mongo
      - redis

  mongo:
    image: mongo:4.2
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  redis:
    image: redis

networks:
  default:
    name: registry-network
    driver: bridge
