version: '3.1'

services:

  mocha:
    build: .
    volumes:
      - ./index.js:/app/index.js
      - ./api-doc.yml:/app/api-doc.yml
      - ./lib:/app/lib
      - ./plugins:/app/plugins
      - ./test:/app/test
      - ./config/registry/keycloak.json:/app/keycloak.json
    environment:
      NODE_ENV: development
      KEYCLOAK_HOST: http://auth.192-168-178-60.nip.io
      KEYCLOAK_REALM: dataspace
      RESOURCE_SERVER_AUDIENCE: api-gateway
      RESOURCE_CLIENT_ID: api-gateway
      RESOURCE_CLIENT_SECRET: 7SkmAdTp8xhL
    command: npm run test

  coverage:
    build: .
    volumes:
      - ./index.js:/app/index.js
      - ./api-doc.yml:/app/api-doc.yml
      - ./lib:/app/lib
      - ./plugins:/app/plugins
      - ./test:/app/test
      - ./config/registry/keycloak.json:/app/keycloak.json
    environment:
      NODE_ENV: development
      KEYCLOAK_HOST: http://auth.192-168-178-60.nip.io
      KEYCLOAK_REALM: dataspace
      RESOURCE_SERVER_AUDIENCE: api-gateway
      RESOURCE_CLIENT_ID: api-gateway
      RESOURCE_CLIENT_SECRET: 7SkmAdTp8xhL
    command: npm run coverage