version: "3.1"

services:
  registry:
    build: .
    volumes:
      - ./index.js:/app/index.js
      - ./api-doc.yml:/app/api-doc.yml
      - ./lib:/app/lib
      - ./plugins:/app/plugins
      - ./prisma:/app/prisma
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@db:5432/thing_registry?postgres=public
      THINGSBOARD_API_URL: http://thingsboard:9090
    ports:
      - 8080:8080
      - 9229:9229
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  thingsboard:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory